# Generated by Django 3.2.7 on 2021-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemusic', '0003_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='ident_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
