# Generated by Django 3.2.7 on 2021-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20211026_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры курса'),
        ),
    ]
