# Generated by Django 3.2.7 on 2021-10-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mean_rating',
            field=models.CharField(default=0, max_length=5, verbose_name='Рейтинг'),
        ),
    ]
