# Generated by Django 3.2.7 on 2021-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_mean_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mean_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
